title: Kat's Space
description: 'a magical room to escape to :D'
template:
  repo: kat's-space-template
  name: kat's-space
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
